### ISSUE TITLE
Unable to load pydarknet in docker image

### ISSUE THREAD

**Issue by karenc** [WildbookOrg/wildbook-ia#118]
I have seen 2 different errors:

 - undefined symbol: `train_network_datum_gpu`
 - undefined symbol: `cudaPeekAtLastError`

```
(env3) root@8dbd114f82d1:/wbia/pydarknet# python /wbia/wildbook-ia/wbia/dev.py --dbdir /data/db --logdir /data/logs --web --port 5000 --web-deterministic-ports --containerized --cpudark --production
VTOOL BACKEND FOR pyflann = <module 'pyflann' from '/wbia/flann/pyflann/__init__.py'>
VTOOL BACKEND FOR FLANN_CLS = <class 'pyflann.index.FLANN'>
[C!] Caught OSError:                      
/wbia/pydarknet/pydarknet/lib/libpydarknet.so: undefined symbol: train_network_datum_gpu
[C!] cwd='/wbia/pydarknet'                
[C!] load_clib(libname='pydarknet' root_dir='/wbia/pydarknet/pydarknet/lib')
[C!] lib_fpath = '/wbia/pydarknet/pydarknet/lib/libpydarknet.so'
[C] Cannot LOAD 'pydarknet' dynamic library. Is there a missing dependency?
```

```
(env3) root@725c0cb46bfd:/# python /wbia/wildbook-ia/wbia/dev.py --dbdir /data/db --logdir /data/logs --web --port 5000 --web-deterministic-ports --containerized --cpudark --production
VTOOL BACKEND FOR pyflann = <module 'pyflann' from '/wbia/flann/pyflann/__init__.py'>
VTOOL BACKEND FOR FLANN_CLS = <class 'pyflann.index.FLANN'>
[C!] Caught OSError:
/wbia/pydarknet/pydarknet/lib/libpydarknet.so: undefined symbol: cudaPeekAtLastError
[C!] cwd='/'
[C!] load_clib(libname='pydarknet' root_dir='/wbia/pydarknet/pydarknet/lib')
[C!] lib_fpath = '/wbia/pydarknet/pydarknet/lib/libpydarknet.so'
[C] Cannot LOAD 'pydarknet' dynamic library. Is there a missing dependency?
```

<summary>The full traceback:</summary>

<details>

```
(env3) root@8dbd114f82d1:/wbia/pydarknet# python /wbia/wildbook-ia/wbia/dev.py --dbdir /data/db --logdir /data/logs --web --port 5000 --web-deterministic-ports --containerized --cpudark --production
VTOOL BACKEND FOR pyflann = <module 'pyflann' from '/wbia/flann/pyflann/__init__.py'>
VTOOL BACKEND FOR FLANN_CLS = <class 'pyflann.index.FLANN'>
[C!] Caught OSError:
/wbia/pydarknet/pydarknet/lib/libpydarknet.so: undefined symbol: train_network_datum_gpu
[C!] cwd='/wbia/pydarknet'
[C!] load_clib(libname='pydarknet' root_dir='/wbia/pydarknet/pydarknet/lib')
[C!] lib_fpath = '/wbia/pydarknet/pydarknet/lib/libpydarknet.so'
[C] Cannot LOAD 'pydarknet' dynamic library. Is there a missing dependency?

+------

<!!! EXCEPTION !!!>
Traceback (most recent call last):
  File "/wbia/pydarknet/pydarknet/pydarknet_helpers.py", line 80, in _find_c_shared_library_by_device
    darknet_clib, def_cfunc = ctypes_interface.load_clib(libname, root_dir)
  File "/wbia/pydarknet/pydarknet/ctypes_interface.py", line 134, in load_clib
    raise ImportError(errmsg)
ImportError: [C] Cannot LOAD 'pydarknet' dynamic library. Is there a missing dependency?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):        
  File "/wbia/wildbook-ia/wbia/__init__.py", line 53, in <module>
    from wbia import other                
  File "/wbia/wildbook-ia/wbia/other/__init__.py", line 7, in <module>
    from wbia.other import detectgrave    
  File "/wbia/wildbook-ia/wbia/other/detectgrave.py", line 18, in <module>
    from wbia.control import controller_inject
  File "/wbia/wildbook-ia/wbia/control/__init__.py", line 12, in <module>
    from wbia.control import IBEISControl 
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 168, in <module>
    ub.import_module_from_name(modname)   
  File "/virtualenv/env3/lib/python3.6/site-packages/ubelt/util_import.py", line 260, in import_module_from_name
    module = importlib.import_module(modname)
  File "/virtualenv/env3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/wbia/wildbook-ia/wbia/control/manual_meta_funcs.py", line 11, in <module>
    from wbia.algo import Config          
  File "/wbia/wildbook-ia/wbia/algo/__init__.py", line 6, in <module>
    from wbia.algo import detect          
  File "/wbia/wildbook-ia/wbia/algo/detect/__init__.py", line 7, in <module>
    from wbia.algo.detect import yolo     
  File "/wbia/wildbook-ia/wbia/algo/detect/yolo.py", line 15, in <module>
    import pydarknet                      
  File "/wbia/pydarknet/pydarknet/__init__.py", line 14, in <module>
    from ._pydarknet import *             
  File "/wbia/pydarknet/pydarknet/_pydarknet.py", line 176, in <module>
    DARKNET_CLIB, CFUNC = _load_c_shared_library(METHODS, device=DEVICE)
  File "/wbia/pydarknet/pydarknet/pydarknet_helpers.py", line 94, in _load_c_shared_library
    darknet_clib, def_cfunc = _find_c_shared_library_by_device(device=device)
  File "/wbia/pydarknet/pydarknet/pydarknet_helpers.py", line 86, in _find_c_shared_library_by_device
    raise RuntimeError('Could not load library')
RuntimeError: Could not load library      
                                          
[!wbia.__init__] Error when importing wbia
<class 'RuntimeError'>: Could not load library
</!!! EXCEPTION !!!>                      
                                          
L______                                   
                                          
Traceback (most recent call last):        
  File "/wbia/pydarknet/pydarknet/pydarknet_helpers.py", line 80, in _find_c_shared_library_by_device
    darknet_clib, def_cfunc = ctypes_interface.load_clib(libname, root_dir)
  File "/wbia/pydarknet/pydarknet/ctypes_interface.py", line 134, in load_clib
    raise ImportError(errmsg)             
ImportError: [C] Cannot LOAD 'pydarknet' dynamic library. Is there a missing dependency?
                                          
During handling of the above exception, another exception occurred:
                                          
Traceback (most recent call last):        
  File "/wbia/wildbook-ia/wbia/dev.py", line 41, in <module>
    from wbia._devscript import devcmd, DEVCMD_FUNCTIONS, DEVPRECMD_FUNCTIONS
  File "/wbia/wildbook-ia/wbia/__init__.py", line 53, in <module>
    from wbia import other                
  File "/wbia/wildbook-ia/wbia/other/__init__.py", line 7, in <module>
    from wbia.other import detectgrave    
  File "/wbia/wildbook-ia/wbia/other/detectgrave.py", line 18, in <module>
    from wbia.control import controller_inject
  File "/wbia/wildbook-ia/wbia/control/__init__.py", line 12, in <module>
    from wbia.control import IBEISControl 
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 168, in <module>
    ub.import_module_from_name(modname)   
  File "/virtualenv/env3/lib/python3.6/site-packages/ubelt/util_import.py", line 260, in import_module_from_name
    module = importlib.import_module(modname)
  File "/virtualenv/env3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/wbia/wildbook-ia/wbia/control/manual_meta_funcs.py", line 11, in <module>
    from wbia.algo import Config          
  File "/wbia/wildbook-ia/wbia/algo/__init__.py", line 6, in <module>
    from wbia.algo import detect          
  File "/wbia/wildbook-ia/wbia/algo/detect/__init__.py", line 7, in <module>
    from wbia.algo.detect import yolo     
  File "/wbia/wildbook-ia/wbia/algo/detect/yolo.py", line 15, in <module>
    import pydarknet                      
  File "/wbia/pydarknet/pydarknet/__init__.py", line 14, in <module>
    from ._pydarknet import *             
  File "/wbia/pydarknet/pydarknet/_pydarknet.py", line 176, in <module>
    DARKNET_CLIB, CFUNC = _load_c_shared_library(METHODS, device=DEVICE)
  File "/wbia/pydarknet/pydarknet/pydarknet_helpers.py", line 94, in _load_c_shared_library
    darknet_clib, def_cfunc = _find_c_shared_library_by_device(device=device)
  File "/wbia/pydarknet/pydarknet/pydarknet_helpers.py", line 86, in _find_c_shared_library_by_device
    raise RuntimeError('Could not load library')
RuntimeError: Could not load library      
```

</details>

**Comment by bluemellophone** [comment]
This should be fixed here: https://github.com/WildbookOrg/wildbook-ia/tree/build-process-merge.

I will make a PR in the morning

**Comment by bluemellophone** [comment]
see here: https://github.com/WildbookOrg/wildbook-ia/runs/1127343923?check_suite_focus=true#step:5:316

**Comment by bluemellophone** [comment]
PyDarknet was failing to import for a different reason after the lib was loaded, but has been fixed here https://github.com/WildbookOrg/wbia-tpl-pydarknet/commit/0b7843fef66c8adb738202d266e7d91bfb20e552 for version 3.3.1

**Comment by bluemellophone** [comment]
This actually required a fix in the PyDarknet code: https://github.com/WildbookOrg/wbia-tpl-pydarknet/commit/4d7003091a1eb24413541a5c32b668ef0e8cea92
